name: Checkout and create war
on: push
env:
  JAVA_VERSION: '1.8' # set this to the java version to use
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: master
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: ${{ env.JAVA_VERSION }}
      - name: Create directory if not exist
        run: mkdir -p /home/runner/work/JSPProject/JSPProject/output/war
      - name: Listing directory
        run: ls -larth 
      - name: Create war
        run: jar -cvf output/war/app.war WebContent/*
      - name: Listing war
        run: ls -larth output/war/
        
