name: Checkout and create war
on: push
env:
  JAVA_VERSION: '1.8' # set this to the java version to use
  HOST: '68.183.229.196'
  SSH_USER: 'medisagi'
  SSH_PASSWORD: 'Training123Tomcat'
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: master
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: ${{ env.JAVA_VERSION }}
      - name: Create directory if not exist
        run: mkdir -p /home/runner/work/JSPProject/JSPProject/output/war
      - name: Listing directory
        run: ls -larth 
      - name: Change Directory
        run: cd WebContent
      - name: Create war
        run: jar -cvf ../output/war/app.war *
      - name: Change Directory
        run: cd ..
      - name: Listing war
        run: ls -larth output/war/
      - name: Deploy the package to the remote server
        uses: garygrossgarten/github-action-scp@release
        with:
          local: output/war/app.war
          remote: /home/medisagi/apache-tomcat-8.5.96/webapps/app.war
          host: ${{ env.HOST }}
          username: ${{ env.SSH_USER }}
          password: ${{ env.SSH_PASSWORD }}
        
